### PR TITLE
[terra-slide-panel] Added screen reader support to communicate if slide panel exists

### PR DESCRIPTION
**Pull request by sycombs**
### Summary
This change adds screen reader support to communicate to a user upfront that a slide panel is present and may be interactable within the current element in order to provide advance warning that there may be contextual changes in the region.

Since this PR also utilizes built-in text, internationalization is added to `terra-slide-panel`.

UXPLATFORM-8853

Closes #

### Additional Details

---
Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by eawww — APPROVED** [review]

**Comment by sdadn** [comment]
> Fails
> 🚫	Please include a CHANGELOG entry for each changed package this PR. Looks like a CHANGELOG entry is missing for:
> * terra-slide-panel-manager
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [c456383](https://github.com/cerner/terra-framework/commit/c456383acf682ca76df61e9aed95afa4e21e2df0)

This CHANGELOG entry is not needed as the only thing changed in `slide-panel-manger` are tests and package.json scripts. The rest of the build is still passing:

CleanShot 2023-04-20 at 17 09 54

**Review by artpark — APPROVED** [review]

**Comment by mjpalazzo** [comment]
I could not get the helper text to announce when using H key to get to the header of the Main Content area. I met with @sycombs to discuss the expected behavior. From the example heading I used down arrow to get to the region and down arrow again for JAWS to announce the helper text. I also tested with VoiceOver.
@eawww - does this keyboard navigation using arrow keys how we expect users to interact with the Main Content? Is it OK that using H to navigate to the header skips the helper text?

**Comment by eawww** [comment]
@mjpalazzo I've reached out to Rachel Magario to check on this.

**Comment by mjpalazzo** [comment]
I do not have approval permissions. I am good with proceeding.

**Pull request merged**
