### PR TITLE
Update date picker buttons

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
This update changes the buttons for previous and next month back to rendering an HTML button element instead of using the terra-button react component for rendering these buttons. There were some issues with the hover state in the low-light theme where we found this styling is more favorable for the buttons at this time compared to using the terra-button component.

Resolves https://github.com/cerner/terra-framework/issues/929

### CODE REVIEW

**Comment by benbcai** [comment]
- Some of the screenshots need to be updated.
- This [line](https://github.com/cerner/terra-framework/blob/master/packages/terra-date-picker/src/react-datepicker/calendar.jsx#L282-L283) is throwing an error when clicking on the Previous/Next month button. Also I think one of them on that line should be `nextMonthBtnRef` instead of both being `previousMonthBtnRef`.

`Uncaught TypeError: a.previousMonthBtnRef.contains is not a function`

**Comment by bjankord** [comment]
@benbcai I've updated the code to address the comments in the following commits:
* https://github.com/cerner/terra-framework/pull/932/commits/a48f08ddf31213bf668a0be2e7d2e11b59b8638a
* https://github.com/cerner/terra-framework/pull/932/commits/d58d77a8fe1a849e6d6bdb3fb4062290ae7fc9fa
* https://github.com/cerner/terra-framework/pull/932/commits/b5edae3124ab8645813f7f361b752041d668e158
* https://github.com/cerner/terra-framework/pull/932/commits/908ce1fde4d332586d8e52feb476d376638a7f23
* https://github.com/cerner/terra-framework/pull/932/commits/2d3cff84ae755c9b9789285f1a8f84df905cfc6f

**Comment by benbcai** [comment]
In the [example](https://terra-framework-deploye-pr-932.herokuapp.com/components/terra-date-picker/date-picker/date-picker) with the min/max date set, the previous and next month buttons are not rendered. There is still an error if you just select a date that is within the range in the calendar.

`Uncaught TypeError: Cannot read property 'contains' of null`

I don't remember whether or not the next and previous month button were shown or disabled when there are no valid dates past the currently shown month. I need to go back and check.

**Comment by bjankord** [comment]
@benbcai Resolved the `Uncaught TypeError: Cannot read property 'contains' of null` error in this commit: https://github.com/cerner/terra-framework/pull/932/commits/8afff4dcdcc9b0a98cdd038055eacc2108377d20

**Pull request merged**
