### PR TITLE
[terra-date-picker] Fixed crash issue for upper and lower bound dates in IE

### LINKED ISSUE #1405: Date and Date/Time Picker Crashes When Navigating to an Upper or Lower Bound Month
# Bug Report

## Description

When navigating to January 1900 or December 2100 in the `terra-date-picker` or `terra-date-time-picker`, the following error is thrown and causes the page to stop rendering while using Internet Explorer 10/11.

- Note: It only occurs when you navigate the months with the arrows while on the year 1900 or 2100. If you select January/December and then change the year, it behaves as expected.

```
TypeError: Unable to get property 'hasAttribute' of undefined or null reference
```

https://user-images.githubusercontent.com/83246901/116145328-d1d14e00-a6a2-11eb-8728-281a20fe6e19.mp4

## Steps to Reproduce

1. Open Date or Date/Time Picker
2. Select 1900 as the year
3. Use back arrow to set the month to January

**OR**

1. Open Date or Date/Time Picker
2. Select 2100 as the year
3. Use forward arrow to set the month to December

**Note:** It is reproducible from the terra-dev-site page for Terra in IE.
https://engineering.cerner.com/terra-ui/components/terra-date-time-picker/date-time-picker/date-time-picker

## Additional Context / Screenshots

See video demo above.

## Expected Behavior

The arrows should navigate to January of 1900 and December of 2100.

## Environment

* Component Name and Version: terra-date-time-picker@4.60.0 **and** terra-date-picker@4.59.0
* Browser Name and Version: Internet Explorer 10 & 11
* Node/npm Version: Node v10.22.1/NPM 6.14.6
* Webpack Version: 4.41.5
* Operating System and version (desktop or mobile): Windows 7/10 and Windows Server 2012/2016

## @ Mentions

@benbcai

### PR DESCRIPTION
**Pull request by saket2403**
### Summary
Fixed crash issue for upper and lower bound dates in IE.
Closes #1405 

### Deployment Link

https://terra-framework-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by ShettyAkarsh — APPROVED** [review]

**Comment by benbcai** [comment]
Should we add a test step around [here](https://github.com/cerner/terra-framework/blob/6a636ae62c4b9cddeb8637313e4752d1e80b1d49/packages/terra-date-picker/tests/wdio/date-picker-spec.js#L432) to test clicking the Previous/Next buttons to get to January 1900 and December 2100 even though we don't run tests in IE?

**Comment by saket2403** [comment]
> Should we add a test step around [here](https://github.com/cerner/terra-framework/blob/6a636ae62c4b9cddeb8637313e4752d1e80b1d49/packages/terra-date-picker/tests/wdio/date-picker-spec.js#L432) to test clicking the Previous/Next buttons to get to January 1900 and December 2100 even though we don't run tests in IE?

Done

**Review by pranav300 — APPROVED** [review]

**Review by benbcai — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

**Comment by benbcai** [comment]
@saket2403 @chrismichalewicz Does this need functional verification? If it does not, is there anything else we need before merging?

**Comment by benbcai** [comment]
Oops, I accidentally clicked on the wrong button and closed it.

**Comment by saket2403** [comment]
> @saket2403 @chrismichalewicz Does this need functional verification? If it does not, is there anything else we need before merging?

This is ready to merge

**Pull request merged**
