### PR TITLE
[terra-data-grid] Delete Obsolete Components and Packages

### PR DESCRIPTION
**Pull request by kenk2**
### Summary

**What was changed:**
Deleted obsolete components and packages from the terra-data-grid package.

**Why it was changed:**
To get rid of obsolete code and packages that are no longer being used. 

### Testing

This change was tested using:

- [x] WDIO
- [x] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-9543 

---

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by kenk2** [comment]
> Fails
> 🚫	Please include a CHANGELOG entry for each changed package this PR. Looks like a CHANGELOG entry is missing for:
> * terra-data-grid
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [02c8135](https://github.com/cerner/terra-framework/commit/02c8135836bcf11d6eb7c2879534e1c6cb525428)

No consumer facing changes are made in this PR. Therefore we will not need a changelog update.

**Comment by sdadn** [comment]
Are there any translations that need to be moved from data-grid to table?

**Comment by kenk2** [comment]
> Are there any translations that need to be moved from data-grid to table?

I was thinking to do that in a separate PR. We'll know which ones are obsolete or need to be moved with a code search by seeing what's still being referenced inside components vs not.

**Review by sdadn — APPROVED** [review]

**Comment by cm9361** [comment]
Looks like you have conflicts to resolve.

**Review by cm9361 — APPROVED** [review]

**Pull request merged**
