### PR TITLE
Support text transform nav

### PR DESCRIPTION
**Pull request by alex-bezek**
### Summary
Some of our clients choose to theme their components heavily to match the design of the content they embed. One specific request is the ability to make their navigation text be all caps. This exists in their current navigation implementation, and in order to switch over to fully utilize the terra-application-layout, we need this functionality.

Our initial reaction to this request was that since the nav text is configurable, the client could just provide all caps text to store in that service, which would then be passed to the terra nav and display as all caps.

However, this was shot down as "it should be a theme option". The goal is to let the text be theme-able, and not to try to achieve this look by having to programmatically or manually go update all of a clients nav items.

Open issue here https://github.com/cerner/terra-framework/issues/379

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

**Comment by alex-bezek** [comment]
I saw this class being added https://github.com/cerner/terra-framework/blob/master/packages/terra-application-links/src/tabs/_Tab.jsx#L149 but didn't see it in the modules.scss file. I noticed while reading through the dom structure and saw it was just "tab-inner" with no module obfuscation. Is this used for something?

**Comment by alex-bezek** [comment]
oh come on @StephenEsser it's a perfect 5/7 so far. no bots had to yell at me

**Comment by bjankord** [comment]
I'd like to get @neilpfeiffer to take a look so he is aware of the change.

**Comment by neilpfeiffer** [comment]
Reviewed: PR #435
Resolves: Issue #379

**Reviewed:**
- Adds ability for Client-based themes to UPPERCASE their top navigation labels

**Related:**
- @BenBoersma this change will need to be incorporated into your ocs-theme-variables branch
- @tbiethman @dkasper-was-taken this change will need to be incorporated into your framework refactor branch

\
\
Verified by @neilpfeiffer, Ready for Release.

**Pass** |
-----------|
UX Review|

**Pull request merged**
