### PR TITLE
[terra-table] Rerganized Cell.jsx for easier maintenance & readability 

### PR DESCRIPTION
**Pull request by sdadn**
### Summary

This PR reorganizes the cell.jsx file for easier maintenance & readability by moving the code into labelled sections. There are no functional changes in this PR.

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [x] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

---

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by sdadn** [comment]
> Fails
> 🚫	Please include a CHANGELOG entry for each changed package this PR. Looks like a CHANGELOG entry is missing for:
> * terra-table
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [41de8bd](https://github.com/cerner/terra-framework/commit/41de8bdb8f422dac0a808cf4cca0b284204b015b)

CHANGELOG updates are not needed.

**Comment by cm9361** [comment]
Are these changes necessary?  It might make it harder to maintain to have manually added headers for code.

**Comment by sdadn** [comment]
Test failures are due to other wdio components. The jest tests passing indicate that the cell.jsx is still functionally identical after this change.

**Comment by sdadn** [comment]
> Are these changes necessary? It might make it harder to maintain to have manually added headers for code. I feel like some of the headers would make it confusing where to add code.

@cm9361  The headers help to indicate what each block of code does at a glance, but I can remove them if it can cause more confusion in the future. Besides the headers, these changes are mainly grouping functionally similar code together to minimize jumping back and forth, such as putting all DOM related variables at the end.

**Comment by sdadn** [comment]
@cm9361 Removed all comment headers here: 83b0a5cf510702141ccb17a5651ec04e1a36ab6b

**Review by cm9361 — APPROVED** [review]

**Pull request merged**
