### PR TITLE
[terra-slide-panel] Add focus check for disclosing node before focusing

### PR DESCRIPTION
**Pull request by trandrew1023**
### Summary

**What was changed:**
Added check for disclosing node's focus before calling focus. If the disclosing node has undefined focus, the main node will be focused.

This is no longer reproducible within Terra using IE11 and custom example with SVGs in buttons, but this change has still been added to prevent unknown issues with undefined focus on disclosing nodes. An example was added with just an SVG with onclick which would cause the crash. With the added check, the crash no longer occurs.

**Why it was changed:**
Issues with SVGs and browser (IE11) crashing due to focus not being defined.

### Testing

The example added to test these slide panel changes can be found under Tests -> Slide Panel -> Slide Panel SVG Toggle

This change was tested using:

- [x] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [x] Other (please describe below)
- [ ] No tests are needed

Just SVG with onclick:
Before:
image

After:
image

Verified in IE11 with different buttons with Terra Icons and SVGs
image

### Reviews

In addition to engineering reviews, this PR needs:

- [x] UX review
- [ ] Accessibility review
- [x] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-9296

---

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by trandrew1023** [comment]
Updated to test example to include <p> to toggle and test focus

image

**Review by artpark — APPROVED** [review]

**Comment by sdadn** [comment]
Does this fix result in any change in behavior for non-IE browsers?

**Comment by trandrew1023** [comment]
> Does this fix result in any change in behavior for non-IE browsers?

No change in behavior from testing since SVGs in non-IE browsers don't crash with an undefined issue in non-IE so the focus check didn't change anything. 

One thing to note though is when disclosing from an SVG or even `<p>`, the focus returns to the page body instead of the disclosing node even though the disclosing node is set. This happens with/without the added focus check

**Review by smason0 — APPROVED** [review]

**Review by sdadn — APPROVED** [review]

**Review by sycombs — APPROVED** [review]

**Comment by chrismichalewicz** [comment]
@trandrew1023  I have reviewed this using Edge in IE Mode and this looks good. Added the Functionally Reviewed label.

**Review by cm9361 — APPROVED** [review]

**Comment by trandrew1023** [comment]
Removed UX review since this was mostly just a functional change

**Pull request merged**
