### PR TITLE
Notification icon

### LINKED ISSUE #217: NotificationDialog Variants Icon does not get displayed in IE 11
# Bug Report

## Description

On clicking the notification dialog in IE the icon does not get displayed. 
## Steps to Reproduce

1. Access the [terra-framework website](https://engineering.cerner.com/terra-framework/#/components/terra-notification-dialog/notification-dialog/notification-dialog)
2. Click on any of the `Trigger NotificationDialog` buttons
3. The notification Dialog pops up without any icon. 

## Additional Context / Screenshots

screen shot 2018-07-05 at 10 21 29 am

## Expected Behavior

The Icon should be displayed in the pop-up.
screen shot 2018-07-05 at 10 22 46 am

## Environment

* Component Name and Version: Notification Dialog 1.1.0
* Browser Name and Version: IE 11
* Operating System and version (desktop or mobile): Windows

### PR DESCRIPTION
**Pull request by bjankord**
### Summary
Resolves #217 & https://github.com/cerner/terra-core/issues/1962

There was a slight, barely visible change on the notification dialog buttons related to this PR: https://github.com/cerner/terra-core/pull/1943 but no visual change to how the icon is displayed.

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
Does it appear like the buttom of the icon is just barely being cut off?

screen shot 2018-10-08 at 4 17 48 pm
screen shot 2018-10-08 at 4 17 30 pm

**Comment by emilyrohrbough** [comment]
@bjankord I am noticing this on Chrome

**Comment by bjankord** [comment]
@emilyrohrbough Update viewbox so the circles don't get clipped.

Old screenshot:
old-screenshot


New screenshot:
new-screenshot

**Comment by PaulSolDev** [comment]
Functional review complete.  No issues identified.

**Pull request merged**
