### PR TITLE
[terra-embedded-content-consumer] Updated the path name for the examples in doc site to resolve missing files

### PR DESCRIPTION
**Pull request by kolkheang**
### Summary

**What was changed:**
Updated the path name of the dependency file which uses in the examples in terra-embedded-content-consumer

**Why it was changed:**
The update is needed to resolve the 404 missing file

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [x] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

Screenshot 2023-07-11 at 1 18 26 PM
Screenshot 2023-07-11 at 1 18 41 PM

**This PR resolves:**

UXPLATFORM-9302

---

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by vinaybhargavar — APPROVED** [review]

**Review by chenyixuan625 — APPROVED** [review]

**Comment by kolkheang** [comment]
Looking at the PR build for docs, there are still 404s
https://engineering.cerner.com/terra-framework/pull/1695/. Perhaps, the path is still not correct when looking at the PR build.

**Comment by kolkheang** [comment]
I fixed the new issue by including `/terra-framework/` prefix in the path.

**Comment by vinaybhargavar** [comment]
> I fixed the new issue by including `/terra-framework/` prefix in the path.

I see the content is now updated on the deployed site.
Screen Shot 2023-07-12 at 3 41 48 PM

**Review by sdadn — APPROVED** [review]

**Review by sycombs — APPROVED** [review]

**Comment by kolkheang** [comment]
@scottwilmarth - FYI - this is just to get the examples working again

@sdadn  / @sycombs - can you merge?

**Pull request merged**
