### PR TITLE
[terra-data-grid] Update Worklist Data Grid Focusable Cell example

### PR DESCRIPTION
**Pull request by sdadn**
### Summary

This PR updates the column numbering on the `Worklist Data Grid Focusable Cell` example to be consistent with screenreader announcements.

### Testing

This change was tested using:

- [ ] WDIO
- [ ] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [x] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [x] Accessibility review
- [ ] Functional review

### Additional Details

**This PR resolves:**

UXPLATFORM-XXXX 

---

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by adoroshk — APPROVED** [review]

**Review by kenk2 — APPROVED** [review]

**Comment by mjpalazzo** [comment]
@sdadn - thanks for fixing the column header text. The JAWS announcements now match the visible text.
Regarding the truncated focus indicator around the hyperlink in cell 4, 2. @cm9361 investigated the issue and determined that it should be fixed by the consumer by adding padding to the hyperlink control. See his comment in (https://jira2.cerner.com/browse/UXPLATFORM-10308). Would you consider fixing that in this PR or do we need a separate PR for that issue?

**Comment by sdadn** [comment]
@mjpalazzo I can get that fixed in this PR, thanks for the feedback!

**Comment by mjpalazzo** [comment]
@sdadn - Checking on the status of this PR. We know have an MPages Investigation Jira for it.
https://jira2.cerner.com/browse/MPAGESCORE-91948

**Comment by sdadn** [comment]
This should be resolved in https://github.com/cerner/terra-framework/pull/2102.

**Pull request closed without merging**
