### PR TITLE
Generator output for external-component

### PR DESCRIPTION
**Pull request by mhemesath**
### Summary
Generator code for external-component. This is a component which will enable a 3rd party external react app to be mounted in the same frame. The component will handle downloading all required JavaScript and CSS as defined in a webpack generated manifest before mounting the external app.

### Additional Details
This is only the generator PR. The actual code will be pushed up in a following pull request..

Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the [CONTRIBUTORS.md] file signifies agreement to all rights and reservations provided by the [License].

Thanks for contributing to Terra. 
@cerner/terra

[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md
[License]: ../blob/master/LICENSE

### CODE REVIEW

**Comment by mjhenkes** [comment]
You may want to re-run the generator after this PR gets in. https://github.com/cerner/generator-terra-module/pull/77 for the terra-framework projects we're just prepending 'terra-' to the name instead of 'terra-framework-'

**Comment by emilyrohrbough** [comment]
Is there an issue logged to attach to the PR?

**Comment by mhemesath** [comment]
Also, I hate the name external-component but couldn't think of a better one. Candidates:

* ExternalComponent
* ThirdPartyComponent
* AMDComponent
* EmbeddedComponent

Thoughts?

**Comment by tbiethman** [comment]
EmbeddedComponent would better align with the EmbeddedContentContainer that we use for third-party iframes today.

**Comment by mhemesath** [comment]
Closing this and reopening as embedded component with rerun generator.

**Pull request closed without merging**
