### PR TITLE
Added width 560px to Disclosure manager

### LINKED ISSUE #520: Add new supported width of 560px to disclosure-manager
# Feature Request

## Description
UX wants disclosure manager's within our app to have a width of ~540px~ 560px. This isn't currently an [available disclosure width](https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/src/DisclosureManager.jsx#L18). Since custom values are also not supported I propose adding ~540px~ 560px to the list of available widths.

### PR DESCRIPTION
**Pull request by supreethmr**
### Summary
Resolves #520 

Thanks for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by jmsv6d** [comment]
Add change log entries for ModalManager and DialogModal also. Other than that looks good 👍

**Comment by supreethmr** [comment]
> Add change log entries for ModalManager and DialogModal also. Other than that looks good 👍
 
Change logs added for dialog modal and modal manager : 9b4c9ef0f2d5466609f9bd1a3be0b00b8ad08671

**Comment by nramamurth** [comment]
Now that there is documentation for `dimensions`, I'd add '560' to the list in README. 

https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/docs/README.md

**Comment by supreethmr** [comment]
> Now that there is documentation for `dimensions`, I'd add '560' to the list in README.
> 
> https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/docs/README.md
updated : 7079895e8848755d7b8f6e51e7414c5aac344e1e

**Pull request merged**
