### PR TITLE
[terra-disclosure-manager] Prevent afterdismiss promise from getting resolved prior to dismissing

### LINKED ISSUE #648: [terra-disclosure-manager] afterDismiss promise is resolved prior to dismissing
# Bug Report

## Description

The afterDismiss promise is being resolved prior to dismissing [1] the component. If disclosureManager.closeDisclosure() is then called in afterDismiss to close the rest of the disclosure stack, an exception is thrown and the disclosure is not properly closed.

[1] https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/src/DisclosureManager.jsx#L430

Example project: https://github.com/mschile/terra-framework/tree/afterDismiss

## Steps to Reproduce

1. After starting the example project, navigate to http://localhost:8080/#/tests/terra-modal-manager/modal-manager/modal-manager-after-dismiss
2. Click 'Disclose B' button
3. Click 'Disclose C' button
4. Click 'Dismiss C' button and observe the disclosure is not properly closed.

## Additional Context / Screenshots

Screen Shot 2019-05-02 at 10 18 54 AM

## Expected Behavior

The disclosure is properly closed.

## Possible Solution

Resolve the afterDismiss promise after the component has been dismissed.

https://github.com/cerner/terra-framework/blob/master/packages/terra-disclosure-manager/src/DisclosureManager.jsx#L430

## Environment

* Component Name and Version: terra-disclosure-manager 4.9.0
* Browser Name and Version: Chrome
* Node/npm Version: [e.g. Node 8/npm 5] Node 8.16.0 / npm 6.4.1
* Webpack Version: 4.30.0
* Operating System and version (desktop or mobile): macOS 10.14.4

## @ Mentions

@tbiethman

### PR DESCRIPTION
**Pull request by pranav300**
### Summary
Resolves #648

### CODE REVIEW

**Comment by mjhenkes** [comment]
I agree with @emilyrohrbough, please add a test to verify the behavior.

**Comment by pranav300** [comment]
The problem was that closeDisclosure returns a promise; we need to return that promise in order for jest to wait for it. So, I had an offline conversation with @tbiethman, and we both tried writing jest for it but it didn't work out. Later he told me that he might update the implementation to make it easier to test.

**Comment by emilyrohrbough** [comment]
@pranav300 If we can't get a jest test to verify this, is there a current example that can be used to check this behavior is correct or do we need to create one?

**Comment by tbiethman** [comment]
I wrote a test for this. It's ugly and not straightforward, but it might be better than nothing. 

```jsx
  it('should provide afterDismiss promise to resolve after dismissing', async () => {
    // Because some of the assertions are in Promise handlers, they might not get executed if the Promise doesn't resolve.
    // This will ensure that all the expected assertions are actually getting executed and fail otherwise.
    expect.assertions(23);

    let dismissDisclosureInstance;
    let afterDismissPromise;
    let childApp2DisclosureManager;

    const wrapper = mountDisclosureManager(['test'], manager => (
      <div id="wrapper">
        {manager.children.components}
        {manager.disclosure.components}
      </div>
    ));

    validateInitialState(wrapper);
    validateChildDelegate(wrapper);

    await new Promise((resolve, reject) => {
      const childApp1DisclosureManager = wrapper.find('#child1').getElements()[1].props.disclosureManager;
      childApp1DisclosureManager.disclose({
        preferredType: 'test',
        size: 'large',
        content: {
          key: 'DISCLOSE_KEY',
          component: <TestChild id="component-B" />,
        },
      }).then(resolve).catch(reject);
    });

    wrapper.update();

    await new Promise((resolve, reject) => {
      childApp2DisclosureManager = wrapper.find('#component-B').getElements()[1].props.disclosureManager;
      childApp2DisclosureManager.disclose({
        preferredType: 'test',
        size: 'large',
        content: {
          key: 'Nested',
          component: <TestChild id="component-C" />,
        },
      }).then(({ dismissDisclosure, afterDismiss }) => {
        dismissDisclosureInstance = dismissDisclosure;
        afterDismissPromise = afterDismiss;
        resolve();
      }).catch(reject);
    });

    wrapper.update();

    expect(wrapper.state().disclosureIsOpen).toBeTruthy();
    expect(wrapper.state().disclosureIsFocused).toBeTruthy();
    expect(wrapper.state().disclosureIsMaximized).toBeFalsy();
    expect(wrapper.state().disclosureSize).toBe('large');
    expect(wrapper.state().disclosureComponentKeys).toEqual(['DISCLOSE_KEY', 'Nested']);
    expect(wrapper.state().disclosureComponentData.Nested.key).toEqual('Nested');
    expect(wrapper.state().disclosureComponentData.Nested.component.props.id).toEqual('component-C');
    expect(wrapper.state().disclosureComponentDelegates.length).toEqual(2);

    /**
     * Due to the asynchronous execution of the afterDismiss promise, failed expectations
     * within the promise handler cannot actually fail the test. Instead, we use a flag to
     * and write expectations around the flag after awaiting the promise below.
     */
    let afterDismissResolvedAfterStateUpdate = false;
    afterDismissPromise.then(() => {
      if (wrapper.state().disclosureComponentKeys.indexOf('Nested') === -1) {
        afterDismissResolvedAfterStateUpdate = true;
      }
    });

    await dismissDisclosureInstance();
    await expect(afterDismissPromise).resolves.toBe(undefined);

    expect(afterDismissResolvedAfterStateUpdate).toBeTruthy();

    await childApp2DisclosureManager.closeDisclosure();

    wrapper.update();

    expect(wrapper.state().disclosureIsOpen).toBeFalsy();
  });
```

The big problem here is that calling closeDisclosure returns a promise, and also resolves a separate promise as part of its execution (the mentioned afterDismiss). We can validate that both promises resolve, but since the resolution order is really what we're wanting to test here, it makes things more complicated.

Long term, I'd like to deprecate the `afterDismiss` promise and replace it with a first-class `onDismiss` option in the disclose API to try and make the order of execution more deterministic.

```jsx
      disclosureManager.disclose({
        preferredType: 'test',
        size: 'large',
        content: {
          key: 'DISCLOSE_KEY',
          component: <TestChild id="component-B" />,
        },
        onDismiss: () => {
          // Clean up here
        },
      });

```

**Comment by pranav300** [comment]
Thanks @tbiethman

**Pull request merged**
